#!/usr/bin/env bash

set -e

export PATH="${GOPATH%%:*}/bin:$PATH"

if [[ ! $PORT ]] ; then
  export PORT="$(echo "${RANDOM}${RANDOM}${RANDOM}" | cut -b1-4)"
fi
ARTIFACTS_HOST=${ARTIFACTS_HOST:-localhost}

export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-owner/foo}
export TRAVIS_JOB_ID=${TRAVIS_JOB_ID:-$(date +%s | cut -b3-9)}
export ARTIFACTS_DEBUG=1
export ARTIFACTS_STORERTYPE="${ARTIFACTS_STORERTYPE:-$1}"
export ARTIFACTS_AUTHERTYPE="${ARTIFACTS_AUTHERTYPE:-null}"

if [[ ! $DISABLE_ARTIFACTS_FETCH ]] ; then
  echo '---> Fetching latest artifacts client'
  curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
fi

UPLOADED_PATH="$(dirname $0)/tmp/$TRAVIS_REPO_SLUG"
UPLOADED_PATH="$UPLOADED_PATH/jobs/$TRAVIS_JOB_ID"
UPLOADED_PATH="$UPLOADED_PATH/testfile.out"

rm -rvf "$(dirname $0)/tmp"

if [[ ! $DISABLE_ARTIFACTS_SERVICE ]] ; then
  artifacts-service serve > server.out 2>&1 &
  SERVICE_PID="$!"
  echo "---> Started artifacts-service   PORT=$PORT PID=$SERVICE_PID"

  trap "kill \"${SERVICE_PID}\" ; true" EXIT QUIT TERM

  t=0
  while ! curl -s -f $ARTIFACTS_HOST:$PORT >/dev/null ; do
    if [[ t -ge ${ARTIFACTS_SERVICE_STARTUP_LOOPS:-10} ]] ; then
    echo
      echo '---> Enough already!'
      cat server.out || true
      exit 1
    fi
    echo -en '.'
    sleep 0.05
    let t+=1
  done

  echo
fi

TEST_OUTPUT="$RANDOM $RANDOM $RANDOM"
echo "$TEST_OUTPUT"> testfile.out

echo "---> Wrote test output: '$TEST_OUTPUT'"

set -x

artifacts -v
artifacts upload \
  --upload-provider artifacts \
  --save-host http://$ARTIFACTS_HOST:$PORT testfile.out

set +x
set +e

UPLOADED_CONTENT="$(curl -s -f "http://$ARTIFACTS_HOST:$PORT/job/$TRAVIS_JOB_ID/testfile.out")"

if [[ ! $DISABLE_ARTIFACTS_SERVICE ]] ; then
  echo "---> Dumping server log"
  cat server.out
  echo "---> End of server log"
fi

if [[ "$TEST_OUTPUT" != "$UPLOADED_CONTENT" ]] ; then
  echo "---> ERROR: Uploaded content does not match"
  exit 1
fi

echo "---> Looks good"
exit 0
